name: Deploy Astro Portfolio to GitHub Pages

on:
  push:
    branches: [ master ]  # change to 'main' if your default branch is main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: "Abrhaley Arefaine Hailenchael"
          user_email: "abrhaleyarefaine1997@gmail.com"
