name: Deploy Astro site to GitHub Pages

# Controls when the workflow will run
on:
  push:
    # Trigger deployment whenever a push happens on the 'master' branch.
    branches: [ master ] 

# Sets the permissions granted to the GITHUB_TOKEN for this workflow
permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that run sequentially or in parallel
jobs:

  # 1. The 'build' job creates the static output
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 20 is the current LTS version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Add .nojekyll file to stop Jekyll processing
        run: touch dist/.nojekyll # THIS IS THE NEW LINE

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  # 2. The 'deploy' job publishes the site to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
